#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

rogerinho()
{
gentoo-pipewire-launcher ; gentoo-pipewire-launcher
}

rogerinho &

bspc config border_width         2
bspc config window_gap		 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding		 6
bspc config bottom_padding	 6
bspc config left_padding	 6
bspc config right_padding 	 6
bspc config border_width	 2
bspc config window_gap		 0
bspc config normal_border_color "#031a16"
bspc config focused_border_color "#3e965b"
bspc config focus_follows_pointer true

setxkbmap -layout br &
xinput --set-prop 12 'libinput Accel Profile Enabled' 0, 1 &
xinput --set-prop 12 'libinput Accel Speed' -0.15 &
feh --no-fehbg --bg-fill .environment/Sinaisdooutrolado.jpg &
killall yambar; yambar &
picom &
gsettings set org.gnome.desktop.interface cursor-theme Simp1e-Solarized-Dark-Left &
xrandr --output HDMI-A-0 --set TearFree on
